### ISSUE TITLE
get_starting_seeds returns nothing

### ISSUE THREAD

**Issue by orgw** [keiradams/SQUID#6]
hi, it seems that get_starting_seeds returns nothing..

**Comment by orgw** [comment]
error during 3D generation -- Can't instantiate abstract class AtomFragmentLibrary with abstract methods get, len

**Comment by keiradams** [comment]
Hi, this is an environment issue caused by different or conflicting versions of Pytorch / Pytorch-Geometric. Please check to make sure your environment setup matches what I've included in `environment.yml`. Alternatively, you can try to manually add the methods `def get(...): return __get__(...)` and `def len(...): return __len__(...)` to the `Dataset` classes that are throwing this error.
